version: "3"
services:
  pgsql:
    image: postgres:alpine
    ports:
      - "5450:5432"
    container_name: "db"
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=db
volumes:
  database:
